export const currencyNames = {
  USD: "United States Dollar",
  EUR: "Euro",
  GBP: "British Pound Sterling",
  JPY: "Japanese Yen",
  AUD: "Australian Dollar",
  CAD: "Canadian Dollar",
  CHF: "Swiss Franc",
  CNY: "Chinese Yuan",
  HKD: "Hong Kong Dollar",
  NZD: "New Zealand Dollar",
  SEK: "Swedish Krona",
  KRW: "South Korean Won",
  SGD: "Singapore Dollar",
  NOK: "Norwegian Krone",
  MXN: "Mexican Peso",
  INR: "Indian Rupee",
  RUB: "Russian Ruble",
  ZAR: "South African Rand",
  TRY: "Turkish Lira",
  BRL: "Brazilian Real",
  TWD: "Taiwan New Dollar",
  DKK: "Danish Krone",
  PLN: "Polish Złoty",
  THB: "Thai Baht",
  IDR: "Indonesian Rupiah",
  HUF: "Hungarian Forint",
  CZK: "Czech Koruna",
  ILS: "Israeli New Shekel",
  CLP: "Chilean Peso",
  PHP: "Philippine Peso",
  AED: "United Arab Emirates Dirham",
  COP: "Colombian Peso",
  SAR: "Saudi Riyal",
  MYR: "Malaysian Ringgit",
  RON: "Romanian Leu"
}; 