export const currencyNames = {
	USD: "United States Dollar",
	EUR: "Euro",
	GBP: "British Pound Sterling",
	JPY: "Japanese Yen",
	AUD: "Australian Dollar",
	CAD: "Canadian Dollar",
	CHF: "Swiss Franc",
	CNY: "Chinese Yuan",
	HKD: "Hong Kong Dollar",
	NZD: "New Zealand Dollar",
	SEK: "Swedish Krona",
	KRW: "South Korean Won",
	SGD: "Singapore Dollar",
	NOK: "Norwegian Krone",
	MXN: "Mexican Peso",
	INR: "Indian Rupee",
	RUB: "Russian Ruble",
	ZAR: "South African Rand",
	TRY: "Turkish Lira",
	BRL: "Brazilian Real",
	TWD: "Taiwan New Dollar",
	DKK: "Danish Krone",
	PLN: "Polish Złoty",
	THB: "Thai Baht",
	IDR: "Indonesian Rupiah",
	HUF: "Hungarian Forint",
	CZK: "Czech Koruna",
	ILS: "Israeli New Shekel",
	CLP: "Chilean Peso",
	PHP: "Philippine Peso",
	AED: "United Arab Emirates Dirham",
	COP: "Colombian Peso",
	SAR: "Saudi Riyal",
	MYR: "Malaysian Ringgit",
	RON: "Romanian Leu",
	AFN: "Afghan Afghani",
	ALL: "Albanian Lek",
	AMD: "Armenian Dram",
	ANG: "Netherlands Antillean Guilder",
	AOA: "Angolan Kwanza",
	ARS: "Argentine Peso",
	AWG: "Aruban Florin",
	AZN: "Azerbaijani Manat",
	BAM: "Bosnia-Herzegovina Convertible Mark",
	BBD: "Barbadian Dollar",
	BDT: "Bangladeshi Taka",
	BHD: "Bahraini Dinar",
	BIF: "Burundian Franc",
	BMD: "Bermudian Dollar",
	BND: "Brunei Dollar",
	BOB: "Bolivian Boliviano",
	BSD: "Bahamian Dollar",
	BTN: "Bhutanese Ngultrum",
	BWP: "Botswanan Pula",
	BYN: "Belarusian Ruble",
	BZD: "Belize Dollar",
	CDF: "Congolese Franc",
	CRC: "Costa Rican Colón",
	CUP: "Cuban Peso",
	CVE: "Cape Verdean Escudo",
	DJF: "Djiboutian Franc",
	DOP: "Dominican Peso",
	DZD: "Algerian Dinar",
	EGP: "Egyptian Pound",
	ERN: "Eritrean Nakfa",
	ETB: "Ethiopian Birr",
	FJD: "Fijian Dollar",
	FKP: "Falkland Islands Pound",
	FOK: "Faroese Króna",
	GEL: "Georgian Lari",
	GGP: "Guernsey Pound",
	GHS: "Ghanaian Cedi",
	GIP: "Gibraltar Pound",
	GMD: "Gambian Dalasi",
	GNF: "Guinean Franc",
	GTQ: "Guatemalan Quetzal",
	GYD: "Guyanaese Dollar",
	HNL: "Honduran Lempira",
	HRK: "Croatian Kuna",
    HTG: "Haitian Gourde",
	IMP: "Isle of Man Pound",
	IQD: "Iraqi Dinar",
	IRR: "Iranian Rial",
	ISK: "Icelandic Króna",
	JEP: "Jersey Pound",
	JMD: "Jamaican Dollar",
	JOD: "Jordanian Dinar",
	KES: "Kenyan Shilling",
	KGS: "Kyrgystani Som",
	KHR: "Cambodian Riel",
	KID: "Kiribati Dollar",
	KMF: "Comorian Franc",
	KWD: "Kuwaiti Dinar",
	KYD: "Cayman Islands Dollar",
	KZT: "Kazakhstani Tenge",
	LAK: "Laotian Kip",
	LBP: "Lebanese Pound",
	LKR: "Sri Lankan Rupee",
	LRD: "Liberian Dollar",
	LSL: "Lesotho Loti",
	LYD: "Libyan Dinar",
	MAD: "Moroccan Dirham",
	MDL: "Moldovan Leu",
	MGA: "Malagasy Ariary",
	MKD: "Macedonian Denar",
	MMK: "Myanmar Kyat",
	MNT: "Mongolian Tugrik",
	MOP: "Macanese Pataca",
	MRU: "Mauritanian Ouguiya",
	MUR: "Mauritian Rupee",
	MVR: "Maldivian Rufiyaa",
	MWK: "Malawian Kwacha",
	MZN: "Mozambican Metical",
	NAD: "Namibian Dollar",
	NGN: "Nigerian Naira",
	NIO: "Nicaraguan Córdoba",
	NPR: "Nepalese Rupee",
	OMR: "Omani Rial",
	PAB: "Panamanian Balboa",
	PEN: "Peruvian Sol",
	PGK: "Papua New Guinean Kina",
	PKR: "Pakistani Rupee",
	PYG: "Paraguayan Guarani",
	QAR: "Qatari Riyal",
	RSD: "Serbian Dinar",
	RWF: "Rwandan Franc",
	SBD: "Solomon Islands Dollar",
	SCR: "Seychellois Rupee",
	SDG: "Sudanese Pound",
	SHP: "Saint Helena Pound",
	SLE: "Sierra Leonean Leone",
	SLL: "Sierra Leonean Leone",
	SOS: "Somali Shilling",
	SRD: "Surinamese Dollar",
	SSP: "South Sudanese Pound",
	STN: "São Tomé and Príncipe Dobra",
	SYP: "Syrian Pound",
	SZL: "Swazi Lilangeni",
	TJS: "Tajikistani Somoni",
	TMT: "Turkmenistani Manat",
	TND: "Tunisian Dinar",
	TOP: "Tongan Paʻanga",
	TTD: "Trinidad and Tobago Dollar",
	TVD: "Tuvaluan Dollar",
	TZS: "Tanzanian Shilling",
	UAH: "Ukrainian Hryvnia",
	UGX: "Ugandan Shilling",
	UYU: "Uruguayan Peso",
	UZS: "Uzbekistani Som",
	VES: "Venezuelan Bolívar",
	VND: "Vietnamese Dong",
	VUV: "Vanuatu Vatu",
	WST: "Samoan Tala",
	XAF: "Central African CFA Franc",
	XCD: "East Caribbean Dollar",
	XDR: "Special Drawing Rights",
	XOF: "West African CFA Franc",
	XPF: "CFP Franc",
	YER: "Yemeni Rial",
	ZMW: "Zambian Kwacha",
	ZWL: "Zimbabwean Dollar",
};
